version: "3.8"

services:
  kafka:
    command:
      - "--custom-set log.level=INFO"
      - "--override broker.id=1"
      - "--override broker.rack=DC1"
      - "--override enable.kraft=yes"
      - "--override kraft.cluster.id=MTdlOTZlYmM3YzE2NDQxZD"
      - "--override advertised.listeners=INTERNAL://kafka:29092,EXTERNAL://kafka.local:9092"
      - "--override allow.plaintext.listener=yes"
      - "--override process.roles=broker,controller"
      - "--override inter.broker.listener.name=INTERNAL"
      - "--override controller.listener.names=CONTROLLER"
      - "--override listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT"
      - "--override controller.quorum.voters=1@kafka:9093"
      - "--override listeners=CONTROLLER://:9093,EXTERNAL://:9092,INTERNAL://:29092"
    ports:
      - "9092:9092"
